frr version 8.4.1
frr defaults traditional
hostname technova-router
password technova
enable password technova
log stdout
log level informational
!
! Abilita il routing IP globale
ip forwarding
!
interface eth1
 description Link-to-Switch1-HR-Sales
 ip address 10.10.10.1/24
 ip ospf 1 area 0
!
interface eth2
 description Link-to-Switch2-Guest
 ip address 10.10.20.1/24
 ip ospf 1 area 0
!
interface eth3
 description Link-to-AP1
 ip address 10.10.40.1/24
 ip ospf 1 area 0
!
! Configurazione OSPF (routing dinamico)
router ospf
 ospf router-id 10.10.99.1
 network 10.10.0.0/16 area 0
 auto-area-reference
!
line vty
!